PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX xsd:      <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:      <http://www.w3.org/2002/07/owl#>
PREFIX c4o:      <http://purl.org/spar/c4o/>
PREFIX cito:     <http://purl.org/spar/cito/>
PREFIX event:    <http://purl.org/NET/c4dm/event.owl#>
PREFIX fabio:    <http://purl.org/spar/fabio/>
PREFIX foaf:     <http://xmlns.com/foaf/0.1/>
PREFIX dcterms:  <http://purl.org/dc/terms/>
PREFIX vann:     <http://purl.org/vocab/vann/>
PREFIX swo:      <http://www.ebi.ac.uk/efo/swo/>
PREFIX obo:      <http://purl.obolibrary.org/obo/>
PREFIX bibo:     <http://purl.org/ontology/bibo/>
PREFIX geo:      <http://aims.fao.org/aos/geopolitical.owl#>
PREFIX ocresd:   <http://purl.org/net/OCRe/study_design.owl#>
PREFIX ocrer:    <http://purl.org/net/OCRe/research.owl#>
PREFIX ro:       <http://purl.obolibrary.org/obo/ro.owl#>
PREFIX skos:     <http://www.w3.org/2004/02/skos/core#>
PREFIX ocresst:  <http://purl.org/net/OCRe/statistics.owl#>
PREFIX ocresp:   <http://purl.org/net/OCRe/study_protocol.owl#>
PREFIX vcard:    <http://www.w3.org/2006/vcard/ns#>
PREFIX vitro:    <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX scires:   <http://vivoweb.org/ontology/scientific-research#>
PREFIX vivocore: <http://vivoweb.org/ontology/core#>
PREFIX vivoweb:  <http://vivoweb.org/ontology#>
PREFIX sample:   <http://localhost:8080/vivo_i18n/individual/>
PREFIX demo-data: <http://vivo-demo.uqam.ca/individual/>
PREFIX vitrofrca: <http://vivoweb.org/ontology/vitroAnnotfr_CA#>
PREFIX vitro-public: <http://vitro.mannlib.cornell.edu/ns/vitro/public#>
CONSTRUCT {
     ?uri ?p ?o .
     ?mainImage ?p_mainImage ?o_mainImage .
     ?thumbnailImage ?p_thumbnailImage ?o_thumbnailImage .
     ?vIndividual ?p_vIndividual ?o_vIndividual . 
     ?o_vIndividual ?po_vIndividual ?oo_vIndividual .
     ?o_imgLoc ?po_imgLoc ?oo_imgLoc .
     ?o_imgThumLoc ?po_imgThumLoc ?oo_imgThumLoc .
}
where {
    BIND ( <__INDIVIDUAL_IRI__> AS ?uri) .
    ?uri ?p ?o .
    FILTER ( ! STRENDS( STR(?p), "hasResearchArea") ) .
    FILTER ( ! STRENDS( STR(?p), "relatedBy") ) .
    FILTER ( ! STRENDS( STR(?p), "researchAreaOf") ) .
    FILTER ( ! STRENDS( STR(?p), "type") ) .
    FILTER ( ! STRENDS( STR(?p), "hasKey") ) .
    OPTIONAL {
        ?uri vitro-public:mainImage ?mainImage .
        ?mainImage ?p_mainImage ?o_mainImage .
        FILTER ( ! STRENDS( STR(?p_mainImage), "modTime") ) .
        OPTIONAL {
            ?mainImage vitro-public:downloadLocation ?o_imgLoc .
            ?o_imgLoc ?po_imgLoc ?oo_imgLoc .
            FILTER ( ! STRENDS( STR(?po_imgLoc), "modTime") ) .
            FILTER ( ! STRENDS( STR(?po_imgLoc), "type") ) .
        }
        ?mainImage  vitro-public:thumbnailImage ?thumbnailImage .
        ?thumbnailImage ?p_thumbnailImage ?o_thumbnailImage .
        FILTER ( ! STRENDS( STR(?p_thumbnailImage), "modTime") ) .
        OPTIONAL {
            ?thumbnailImage vitro-public:downloadLocation ?o_imgThumLoc .
            ?o_imgThumLoc ?po_imgThumLoc ?oo_imgThumLoc .
            FILTER ( ! STRENDS( STR(?po_imgThumLoc), "modTime") ) .
        }
    }
    OPTIONAL {
        ?uri  obo:ARG_2000028 ?vIndividual .  
        ?vIndividual ?p_vIndividual ?o_vIndividual . 
        FILTER ( STRENDS( STR(?p_vIndividual), "hasTitle") ) .
        ?o_vIndividual ?po_vIndividual ?oo_vIndividual .
        FILTER ( ! STRENDS( STR(?p_vIndividual), "type") ) .
        FILTER ( ! STRENDS( STR(?po_vIndividual), "type") ) .
    }
}

